export { createChartEngine, openWorkbook } from './public/create-chart-engine.js';
export { ChartWorkbook } from './public/chart-workbook.js';
export {
  UnsupportedOperationError,
  XlsxChartError,
  isXlsxChartError
} from './diagnostics/errors.js';
export type {
  ChartDescriptor,
  ChartEngine,
  ChartEngineOptions,
  ChartAxis,
  ChartAxisKind,
  ChartAxisPosition,
  ChartAxisScaling,
  ChartAxisStyle,
  ChartDataLabels,
  ChartDataPoint,
  ChartFillKind,
  ChartGroup,
  ChartGrouping,
  ChartLegend,
  ChartLayoutMode,
  ChartLayoutTarget,
  ChartFillStyle,
  ChartId,
  ChartLineStyle,
  ChartManualLayout,
  ChartMarkerStyle,
  ChartModel,
  ChartPlotArea,
  ChartPointStyle,
  ChartShapeStyle,
  ChartScatterStyle,
  ChartStyle,
  ChartTextStyle,
  ChartSeries,
  DataMode,
  Diagnostic,
  DiagnosticSeverity,
  ExcelJsCellLike,
  ExcelJsWorkbookLike,
  ExcelJsWorksheetLike,
  GetChartModelOptions,
  RenderFormat,
  RenderContext,
  RenderOptions,
  RenderResult,
  PngRenderer,
  SvgRenderer,
  UnsupportedPolicy,
  WorkbookHandle,
  WorkbookSource
} from './public/types.js';
